# Generated by Django 5.0.6 on 2024-06-16 12:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_rename_tweet_twitter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Twitter',
            new_name='Tweet',
        ),
    ]
